USE MASTER
GO

IF EXISTS (SELECT * FROM sys.databases WHERE NAME = 'EmployeeManagement')
DROP DATABASE EmployeeManagement
GO

CREATE DATABASE EmployeeManagement
GO

USE EmployeeManagement
GO

CREATE TABLE DEPARTMENT(
	DeptNo INT PRIMARY KEY IDENTITY(1,1),
	DeptName NVARCHAR(20),
	Note NVARCHAR(100)
	)
GO

CREATE TABLE EMPLOYEE(
	EmpNo INT PRIMARY KEY,
	EmpName NVARCHAR(20),
	BirthDay DATETIME,
	DeptNo INT,
	MgrNo INT NOT NULL,
	StartDate DATETIME,
	Salary MONEY,
	Level int,
	CONSTRAINT CK_Level CHECK (Level BETWEEN 1 AND 7),
	Status int,
	CONSTRAINT CK_Status CHECK (Status BETWEEN 0 AND 2),
	Note NVARCHAR(100)
	CONSTRAINT FK_EMPLOYEE_DEPARTMENT FOREIGN KEY(DeptNo) REFERENCES DEPARTMENT(DeptNo)
	)
GO

CREATE TABLE SKILL(
	SkillNo INT PRIMARY KEY IDENTITY(1,1),
	SkillName NVARCHAR(20),
	Note NVARCHAR(100)
	)
GO

CREATE TABLE EMP_SKILL(
	SkillNo INT,
	EmpNo INT,
	SkillLevel int,
	CONSTRAINT CK_SkillLevel CHECK (SkillLevel BETWEEN 1 AND 3),
	RegDate DATETIME,
	Description NVARCHAR(20),
	PRIMARY KEY(SkillNo,EmpNo),
	CONSTRAINT FK_EMP_SKILL_EMPLOYEE FOREIGN KEY(EmpNo) REFERENCES EMPLOYEE(EmpNo),
	CONSTRAINT FK_EMP_SKILL_SKILL FOREIGN KEY(SkillNo) REFERENCES SKILL(SkillNo)
	)
GO

ALTER TABLE EMPLOYEE ADD Email VARCHAR(20) UNIQUE
GO
ALTER TABLE EMPLOYEE ADD CONSTRAINT df_employee DEFAULT(0) FOR MgrNo
GO
ALTER TABLE EMPLOYEE ADD CONSTRAINT df_employee_status DEFAULT(0) FOR Status
GO
ALTER TABLE EMP_SKILL DROP COLUMN Description
GO
INSERT INTO DEPARTMENT VALUES(N'Maketing',N'Hỗ trợ bán sản phẩm')
INSERT INTO DEPARTMENT VALUES(N'Hành chính',N'Hỗ trợ nhân viên')
INSERT INTO DEPARTMENT VALUES(N'Chăm sóc ',N'Hỗ trợ khách hàng')
INSERT INTO DEPARTMENT VALUES(N'Phát Triển',N'Tạo sản phẩm')
INSERT INTO DEPARTMENT VALUES(N'Tester',N'Kiểm tra sản phẩm')
GO

INSERT INTO EMPLOYEE VALUES(1,N'Nguyễn Văn Hải','1997/08/12',1,1,'2021/12/27',2000,5,2,N'Đã tốt nghiệp','hai@gmail.com')
INSERT INTO EMPLOYEE VALUES(2,N'Lò Nhật Long','1992/04/12',2,1,'2021/03/27',4000,2,2,N'Sinh viên năm 3','long@gmail.com')
INSERT INTO EMPLOYEE VALUES(3,N'Hồ Quang Hiếu','1992/04/10',3,1,'2021/06/13',3000,2,1,N'Đã tốt nghiệp','hieu@gmail.com')
INSERT INTO EMPLOYEE VALUES(4,N'Phùng Thanh Độ','1989/08/12',1,1,'2021/11/27',2000,4,1,N'Sinh viên năm 4','do@gmail.com')
INSERT INTO EMPLOYEE VALUES(5,N'Nguyễn Tuấn Tú','1987/04/12',2,1,'2021/10/16',5000,4,2,N'Đã tốt nghiệp','tu@gmail.com')
GO

INSERT INTO SKILL VALUES(N'.Net',N'Ngôn ngữ lập trình')
INSERT INTO SKILL VALUES(N'Java',N'Ngôn ngữ lập trình')
INSERT INTO SKILL VALUES(N'Giao Tiếp ',N'Có khả năng thuyết phục')
INSERT INTO SKILL VALUES(N'Test',N'Kiểm tra sản phẩm')
INSERT INTO SKILL VALUES(N'Quản trị',N'Quản lý nhân viên')
GO

INSERT INTO EMP_SKILL VALUES(1,1,3,'2021/04/05')
INSERT INTO EMP_SKILL VALUES(1,2,1,'2021/08/03')
INSERT INTO EMP_SKILL VALUES(2,1,2,'2020/04/05')
INSERT INTO EMP_SKILL VALUES(3,1,3,'2021/02/03')
INSERT INTO EMP_SKILL VALUES(4,3,1,'2020/06/07')
GO

CREATE VIEW EMPLOYEE_TRACKING
AS
SELECT EmpNo,EmpName,Level
FROM EMPLOYEE
WHERE Level>=3 AND Level<=5
GO
SELECT EmpNo,EmpName,Level
FROM EMPLOYEE_TRACKING